#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.4.4 for Opteq 6 channel power module 900 087
# Works with Propeller firmware V3.x
# In conjunction with Tcl version 8.6
#    Aug 10, 2015 09:20:05 AM
# Opteq Mechatronica Oct 2015

import json
import sys
import comportconfig_support
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import tkinter.scrolledtext

from tkinter import Frame, Text, Scrollbar, Pack, Grid, Place
from tkinter.constants import RIGHT, LEFT, Y, BOTH

#import serialport
import PM2_support

serialconfig = {"baudrate":"115200", "comport": "COM2"}

def vp_start_gui(l_serialconfig):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.geometry('600x450+497+117')
    w = frm_Comport1(root)
    PM2_support.init(root, w)
    print('via: vp_start_gui' )
    root.mainloop()

w = None
def create_Test_Comport1(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('Test_Comport1 ')
    w.geometry('600x450+497+117')
    w_win = frm_Comport1(w)
    PM2_support.init(w, w_win, param)
    print('via: create_Test_Comport1' )
    return w_win

def destroy_Test_Comport1():
    global w
    w.destroy()
    w = None

class frm_Comport1:

    def __init__(self, master=None):
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans Mono} -size 14 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        master.configure(background="#d0d0d0")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")

        self.btn_Connect = Button(master)
        self.btn_Connect.place(relx=0.77, rely=0.07, height=24, width=56)
        self.btn_Connect.configure(activebackground="#f4bcb2")
        self.btn_Connect.configure(activeforeground="#000000")
        self.btn_Connect.configure(background="#d0d0d0")
        self.btn_Connect.configure(command=PM2_support.connect_comport)
        self.btn_Connect.configure(disabledforeground="#a3a3a3")
        self.btn_Connect.configure(foreground="#000000")
        self.btn_Connect.configure(highlightbackground="wheat")
        self.btn_Connect.configure(highlightcolor="black")
        self.btn_Connect.configure(pady="0")
        self.btn_Connect.configure(text='''Connect''')

        self.btn_config = Button(master)
        self.btn_config.place(relx=0.77, rely=0.13, height=24, width=57)
        self.btn_config.configure(activebackground="#f4bcb2")
        self.btn_config.configure(activeforeground="#000000")
        self.btn_config.configure(background="#d0d0d0")
        self.btn_config.configure(command=PM2_support.config_comport)
        self.btn_config.configure(disabledforeground="#a3a3a3")
        self.btn_config.configure(foreground="#000000")
        self.btn_config.configure(highlightbackground="wheat")
        self.btn_config.configure(highlightcolor="black")
        self.btn_config.configure(pady="0")
        self.btn_config.configure(text='''Config''')

        self.Entry1 = Entry(master)   # entry for command to serial port
        self.Entry1.place(relx=0.07, rely=0.07, relheight=0.06, relwidth=0.37)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font11)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.btn_Send = Button(master)  # send button
        self.btn_Send.place(relx=0.47, rely=0.07, height=24, width=37)
        self.btn_Send.configure(activebackground="#f4bcb2")
        self.btn_Send.configure(activeforeground="#000000")
        self.btn_Send.configure(background="#d0d0d0")
        self.btn_Send.configure(command=PM2_support.send)
        self.btn_Send.configure(disabledforeground="#a3a3a3")
        self.btn_Send.configure(foreground="#000000")
        self.btn_Send.configure(highlightbackground="wheat")
        self.btn_Send.configure(highlightcolor="black")
        self.btn_Send.configure(pady="0")
        self.btn_Send.configure(text='''Send''')

        self.text1 = Text(master)           # text field for repprting
        self.text1.place(relx=0.05, rely=0.3, relheight=0.6
                , relwidth=0.50)
        self.text1.configure(background="white")
        self.text1.configure(font="TkTextFont")
        self.text1.configure(foreground="black")
        self.text1.configure(highlightbackground="wheat")
        self.text1.configure(highlightcolor="black")
        self.text1.configure(insertbackground="black")
        self.text1.configure(insertborderwidth="3")
        self.text1.configure(selectbackground="#c4c4c4")
        self.text1.configure(selectforeground="black")
        self.text1.configure(width=110)
        self.text1.configure(wrap=NONE)

        self.led_connect = Text(master)
        self.led_connect.place(relx=0.9, rely=0.07, relheight=0.05
                , relwidth=0.04)
        self.led_connect.configure(background="white")
        self.led_connect.configure(cursor="")
        self.led_connect.configure(font=font10)
        self.led_connect.configure(foreground="black")
        self.led_connect.configure(highlightbackground="wheat")
        self.led_connect.configure(highlightcolor="black")
        self.led_connect.configure(insertbackground="black")
        self.led_connect.configure(selectbackground="#c4c4c4")
        self.led_connect.configure(selectforeground="black")
        self.led_connect.configure(width=24)
        self.led_connect.configure(wrap=WORD)

# frame with buttons for outputs
        _bgcolor = "#d0d0d0"
        buttonheigth = 29
        buttonwidth = 55
        ledwidth    = 20
        ledheight   = 20

        self.Labelframe1 = LabelFrame(master)
        self.Labelframe1.place(relx=0.65, rely=0.2, relheight=0.81
                , relwidth=0.34)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Batteries & Outputs''')
        self.Labelframe1.configure(background=_bgcolor)
        self.Labelframe1.configure(width=120)

        self.btn_bat1 = Button(self.Labelframe1)
        self.btn_bat1.place(relx=0.1, rely=0.06, height=buttonheigth, width=buttonwidth)
        self.btn_bat1.configure(activebackground="#d9d9d9")
        self.btn_bat1.configure(activeforeground="#000000")
        self.btn_bat1.configure(background=_bgcolor)
        self.btn_bat1.configure(command=PM2_support.do_bat1)
        self.btn_bat1.configure(disabledforeground="#a3a3a3")
        self.btn_bat1.configure(foreground="#000000")
        self.btn_bat1.configure(highlightbackground="#d9d9d9")
        self.btn_bat1.configure(highlightcolor="black")
        self.btn_bat1.configure(pady="0")
        self.btn_bat1.configure(text='''Bat1''')
        self.btn_bat1.configure(width=41)

        self.btn_bat2 = Button(self.Labelframe1)
        self.btn_bat2.place(relx=0.1, rely=0.14, height=buttonheigth, width=buttonwidth)
        self.btn_bat2.configure(activebackground="#d9d9d9")
        self.btn_bat2.configure(activeforeground="#000000")
        self.btn_bat2.configure(background=_bgcolor)
        self.btn_bat2.configure(command=PM2_support.do_bat2)
        self.btn_bat2.configure(disabledforeground="#a3a3a3")
        self.btn_bat2.configure(foreground="#000000")
        self.btn_bat2.configure(highlightbackground="#d9d9d9")
        self.btn_bat2.configure(highlightcolor="black")
        self.btn_bat2.configure(pady="0")
        self.btn_bat2.configure(text='''Bat2''')
        self.btn_bat2.configure(width=41)

        self.btn_batoff = Button(self.Labelframe1)
        self.btn_batoff.place(relx=0.1, rely=0.23, height=buttonheigth, width=buttonwidth)
        self.btn_batoff.configure(activebackground="#d9d9d9")
        self.btn_batoff.configure(activeforeground="#000000")
        self.btn_batoff.configure(background=_bgcolor)
        self.btn_batoff.configure(command=PM2_support.do_bat_off)
        self.btn_batoff.configure(disabledforeground="#a3a3a3")
        self.btn_batoff.configure(foreground="#000000")
        self.btn_batoff.configure(highlightbackground="#d9d9d9")
        self.btn_batoff.configure(highlightcolor="black")
        self.btn_batoff.configure(pady="0")
        self.btn_batoff.configure(text='''Bat off''')

        self.btn_out1 = Button(self.Labelframe1)
        self.btn_out1.place(relx=0.1, rely=0.38, height=buttonheigth, width=buttonwidth)
        self.btn_out1.configure(activebackground="#d9d9d9")
        self.btn_out1.configure(activeforeground="#000000")
        self.btn_out1.configure(background=_bgcolor)
        self.btn_out1.configure(command=PM2_support.do_out1)
        self.btn_out1.configure(disabledforeground="#a3a3a3")
        self.btn_out1.configure(foreground="#000000")
        self.btn_out1.configure(highlightbackground="#d9d9d9")
        self.btn_out1.configure(highlightcolor="black")
        self.btn_out1.configure(pady="0")
        self.btn_out1.configure(text='''Out1''')

        self.btn_out2 = Button(self.Labelframe1)
        self.btn_out2.place(relx=0.1, rely=0.46, height=buttonheigth, width=buttonwidth)
        self.btn_out2.configure(activebackground="#d9d9d9")
        self.btn_out2.configure(activeforeground="#000000")
        self.btn_out2.configure(background=_bgcolor)
        self.btn_out2.configure(command=PM2_support.do_out2)
        self.btn_out2.configure(disabledforeground="#a3a3a3")
        self.btn_out2.configure(foreground="#000000")
        self.btn_out2.configure(highlightbackground="#d9d9d9")
        self.btn_out2.configure(highlightcolor="black")
        self.btn_out2.configure(pady="0")
        self.btn_out2.configure(text='''Out2''')

        self.btn_out3 = Button(self.Labelframe1)
        self.btn_out3.place(relx=0.1, rely=0.55, height=buttonheigth, width=buttonwidth)
        self.btn_out3.configure(activebackground="#d9d9d9")
        self.btn_out3.configure(activeforeground="#000000")
        self.btn_out3.configure(background=_bgcolor)
        self.btn_out3.configure(command=PM2_support.do_out3)
        self.btn_out3.configure(disabledforeground="#a3a3a3")
        self.btn_out3.configure(foreground="#000000")
        self.btn_out3.configure(highlightbackground="#d9d9d9")
        self.btn_out3.configure(highlightcolor="black")
        self.btn_out3.configure(pady="0")
        self.btn_out3.configure(text='''Out3''')

        self.btn_out4 = Button(self.Labelframe1)
        self.btn_out4.place(relx=0.1, rely=0.64, height=buttonheigth, width=buttonwidth)
        self.btn_out4.configure(activebackground="#d9d9d9")
        self.btn_out4.configure(activeforeground="#000000")
        self.btn_out4.configure(background=_bgcolor)
        self.btn_out4.configure(command=PM2_support.do_out4)
        self.btn_out4.configure(disabledforeground="#a3a3a3")
        self.btn_out4.configure(foreground="#000000")
        self.btn_out4.configure(highlightbackground="#d9d9d9")
        self.btn_out4.configure(highlightcolor="black")
        self.btn_out4.configure(pady="0")
        self.btn_out4.configure(text='''Out4''')

        self.btn_out5 = Button(self.Labelframe1)
        self.btn_out5.place(relx=0.1, rely=0.72, height=buttonheigth, width=buttonwidth)
        self.btn_out5.configure(activebackground="#d9d9d9")
        self.btn_out5.configure(activeforeground="#000000")
        self.btn_out5.configure(background=_bgcolor)
        self.btn_out5.configure(command=PM2_support.do_out5)
        self.btn_out5.configure(disabledforeground="#a3a3a3")
        self.btn_out5.configure(foreground="#000000")
        self.btn_out5.configure(highlightbackground="#d9d9d9")
        self.btn_out5.configure(highlightcolor="black")
        self.btn_out5.configure(pady="0")
        self.btn_out5.configure(text='''Out5''')

        self.btn_out6 = Button(self.Labelframe1)
        self.btn_out6.place(relx=0.1, rely=0.81, height=buttonheigth, width=buttonwidth)
        self.btn_out6.configure(activebackground="#d9d9d9")
        self.btn_out6.configure(activeforeground="#000000")
        self.btn_out6.configure(background=_bgcolor)
        self.btn_out6.configure(command=PM2_support.do_out6)
        self.btn_out6.configure(disabledforeground="#a3a3a3")
        self.btn_out6.configure(foreground="#000000")
        self.btn_out6.configure(highlightbackground="#d9d9d9")
        self.btn_out6.configure(highlightcolor="black")
        self.btn_out6.configure(pady="0")
        self.btn_out6.configure(text='''Out6''')

        self.btn_out_off = Button(self.Labelframe1)
        self.btn_out_off.place(relx=0.1, rely=0.9, height=buttonheigth, width=buttonwidth)
        self.btn_out_off.configure(activebackground="#d9d9d9")
        self.btn_out_off.configure(activeforeground="#000000")
        self.btn_out_off.configure(background=_bgcolor)
        self.btn_out_off.configure(command=PM2_support.do_all_off)
        self.btn_out_off.configure(disabledforeground="#a3a3a3")
        self.btn_out_off.configure(foreground="#000000")
        self.btn_out_off.configure(highlightbackground="#d9d9d9")
        self.btn_out_off.configure(highlightcolor="black")
        self.btn_out_off.configure(pady="0")
        self.btn_out_off.configure(text='''Out Off''')

        self.e_bat2 = Entry(self.Labelframe1)
#        self.e_bat2.place(relx=0.58, rely=0.16, relheight=ledheight, relwidth=ledwidth)
        self.e_bat2.place(relx=0.58, rely=0.16, height=ledheight, width=ledwidth)
        self.e_bat2.configure(background="white")
        self.e_bat2.configure(disabledforeground="#a3a3a3")
        self.e_bat2.configure(font="TkFixedFont")
        self.e_bat2.configure(foreground="#000000")
        self.e_bat2.configure(highlightbackground="#d9d9d9")
        self.e_bat2.configure(highlightcolor="black")
        self.e_bat2.configure(insertbackground="black")
        self.e_bat2.configure(selectbackground="#c4c4c4")
        self.e_bat2.configure(selectforeground="black")
        self.e_bat2.configure(width=24)

        self.e_bat1 = Entry(self.Labelframe1)
        self.e_bat1.place(relx=0.58, rely=0.07, height=ledheight, width=ledwidth)
        self.e_bat1.configure(background="white")
        self.e_bat1.configure(disabledforeground="#a3a3a3")
        self.e_bat1.configure(font="TkFixedFont")
        self.e_bat1.configure(foreground="#000000")
        self.e_bat1.configure(highlightbackground="#d9d9d9")
        self.e_bat1.configure(highlightcolor="black")
        self.e_bat1.configure(insertbackground="black")
        self.e_bat1.configure(selectbackground="#c4c4c4")
        self.e_bat1.configure(selectforeground="black")
        self.e_bat1.configure(width=24)

        self.e_out1 = Entry(self.Labelframe1)
        self.e_out1.place(relx=0.58, rely=0.38, height=ledheight, width=ledwidth)
        self.e_out1.configure(background="white")
        self.e_out1.configure(disabledforeground="#a3a3a3")
        self.e_out1.configure(font="TkFixedFont")
        self.e_out1.configure(foreground="#000000")
        self.e_out1.configure(insertbackground="black")
        self.e_out1.configure(width=24)

        self.e_out2 = Entry(self.Labelframe1)
        self.e_out2.place(relx=0.58, rely=0.46, height=ledheight, width=ledwidth)
        self.e_out2.configure(background="white")
        self.e_out2.configure(disabledforeground="#a3a3a3")
        self.e_out2.configure(font="TkFixedFont")
        self.e_out2.configure(foreground="#000000")
        self.e_out2.configure(insertbackground="black")
        self.e_out2.configure(width=24)

        self.e_out3 = Entry(self.Labelframe1)
        self.e_out3.place(relx=0.58, rely=0.55, height=ledheight, width=ledwidth)
        self.e_out3.configure(background="white")
        self.e_out3.configure(disabledforeground="#a3a3a3")
        self.e_out3.configure(font="TkFixedFont")
        self.e_out3.configure(foreground="#000000")
        self.e_out3.configure(insertbackground="black")
        self.e_out3.configure(width=24)

        self.e_out4 = Entry(self.Labelframe1)
        self.e_out4.place(relx=0.58, rely=0.64, height=ledheight, width=ledwidth)
        self.e_out4.configure(background="white")
        self.e_out4.configure(disabledforeground="#a3a3a3")
        self.e_out4.configure(font="TkFixedFont")
        self.e_out4.configure(foreground="#000000")
        self.e_out4.configure(insertbackground="black")
        self.e_out4.configure(width=24)

        self.e_out5 = Entry(self.Labelframe1)
        self.e_out5.place(relx=0.58, rely=0.72, height=ledheight, width=ledwidth)
        self.e_out5.configure(background="white")
        self.e_out5.configure(disabledforeground="#a3a3a3")
        self.e_out5.configure(font="TkFixedFont")
        self.e_out5.configure(foreground="#000000")
        self.e_out5.configure(insertbackground="black")
        self.e_out5.configure(width=24)

        self.e_out6 = Entry(self.Labelframe1)
        self.e_out6.place(relx=0.58, rely=0.81, height=ledheight, width=ledwidth)
        self.e_out6.configure(background="white")
        self.e_out6.configure(disabledforeground="#a3a3a3")
        self.e_out6.configure(font="TkFixedFont")
        self.e_out6.configure(foreground="#000000")
        self.e_out6.configure(insertbackground="black")
        self.e_out6.configure(width=24)


# -------------------------------


# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''


if __name__ == '__main__':
    vp_start_gui(serialconfig)



